parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Injecte automatiquement les dépendances
        autoconfigure: true # Enregistre automatiquement les commandes, event subscribers, etc.

    # Service Trello avec injection d'arguments depuis les variables d'environnement
    App\Service\Metier\TrelloServiceSM:
        arguments:
            $apiKey: '%env(TRELLO_API_KEY)%'
            $token: '%env(TRELLO_TOKEN)%'

    # Commandes Symfony
    App\Command\:
        resource: '../src/Command'
        tags: ['console.command']

    # Tous les autres services de src/
    App\:
        resource: '../src/'
        exclude: '../src/{Command,DependencyInjection,Entity,Migrations,Tests,Kernel.php}'
